### ISSUE TITLE
[1.x] Create databases

### ISSUE THREAD

**Issue by sfelix-martins** [sfelix-martins/laradock-multiple-project#7]
Create databases like Laravel Homested.

On up command should create the databases, if not exists, from defined project.
An example from `Projects.yml` file:

```yaml
site_1:
  env:
    - PHP_VERSION: 7.3
  services:
    - nginx
    - mysql
    - mailhog
  databases:
    - site_one
    - site_one_test
```

When up the project, check if the project definitions has databases, and create it if not exists.
If database already exists, no action will be required
