### ISSUE TITLE
[1.x] Create virtual host 

### ISSUE THREAD

**Issue by sfelix-martins** [sfelix-martins/laradock-multiple-project#8]
Create virtual hosts mapping like Laravel Homested.

On up command should create the sites mapping according to `Projects.yml` definitions.
An example from `Projects.yml` file:

```yaml
site_1:
  env:
    - PHP_VERSION: 7.3
  services:
    - nginx
    - mysql
    - mailhog
  site:
    - map: siteone.test
    - to: Desktop/projects/siteone/public
```

When up the project create the virtual host if no exists.

It should be able to handle with creation for different services:
  - Nginx
  - Apache 
  - Caddy
